//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progra_Avanzada_Proyecto_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordRecovery
    {
        public int ID { get; set; }
        public string RecoveryCode { get; set; }
        public string Email { get; set; }
        public System.DateTime ExpiryDateTime { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
