//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progra_Avanzada_Proyecto_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosServicios
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
    }
}
